### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by DenielWorld** [SaltyPixelDevz/QuestPmmp#1]
Could you give an example of config for 'playerKill' and 'playerDeath' ? Thanks

**Comment by AlexPads** [comment]
@DenielWorld If I am not Mistaken that would look like.

- name: Mission Five
    task: playerDeath # or playerKill
    num: 2 #this is the Number of Players Killed or the number of times you Die.
    award:
      id: money
      count: 1000
      name: coins

**Comment by AlexPads** [comment]
the dot before the name should be a -
