### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DenielWorld** [SaltyPixelDevz/QuestPmmp#5]
Could you add an option to auto enable quests? For example with the option enabled in config, player won't have to use /quest to redeem the quest, and upon completing any of the tasks the quest gets auto completed. In other words, player automatically has all quests applied to him/her. Thanks.

**Comment by AlexPads** [comment]
It already shows technically when they complete the Quest it is expected of them to use /quest to get to the next quest. But because i may start using this plugin again i might be able to fix it :) or make a Completely New One Thanks!
